
  /react:
    get:
     summary: Get all reacts
     tags: [react]
     responses:
       200:
        schema:
          $ref: '#/components/schemas/react'
 
    post:
      summary: Create react
      tags: [react]
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/react'
      responses:
        201:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/react'
 
  /react/{id}:
    get:
      summary: Get react by id
      tags: [react]
      parameters:
        - in: path
          name: id
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/react'
 
    put:
      summary: Edit react
      tags: [react]
      parameters:
        - in: path
          name: id
      responses:
        202:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/react'
      requestBody:
        content:
            application/json:
              schema:
               $ref: '#/components/schemas/react'
 
    delete:
      summary: Delete react
      tags: [react]
      parameters:
        - in: path
          name: id
      responses:
        202:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/react'

  /user:
    get:
     summary: Get all users
     tags: [user]
     responses:
       200:
        schema:
          $ref: '#/components/schemas/user'
 
    post:
      summary: Create user
      tags: [user]
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/user'
      responses:
        201:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/user'
 
  /user/{id}:
    get:
      summary: Get user by id
      tags: [user]
      parameters:
        - in: path
          name: id
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/user'
 
    put:
      summary: Edit user
      tags: [user]
      parameters:
        - in: path
          name: id
      responses:
        202:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/user'
      requestBody:
        content:
            application/json:
              schema:
               $ref: '#/components/schemas/user'
 
    delete:
      summary: Delete user
      tags: [user]
      parameters:
        - in: path
          name: id
      responses:
        202:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/user'

  /post:
    get:
     summary: Get all posts
     tags: [post]
     responses:
       200:
        schema:
          $ref: '#/components/schemas/post'
 
    post:
      summary: Create post
      tags: [post]
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/post'
      responses:
        201:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/post'
 
  /post/{id}:
    get:
      summary: Get post by id
      tags: [post]
      parameters:
        - in: path
          name: id
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/post'
 
    put:
      summary: Edit post
      tags: [post]
      parameters:
        - in: path
          name: id
      responses:
        202:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/post'
      requestBody:
        content:
            application/json:
              schema:
               $ref: '#/components/schemas/post'
 
    delete:
      summary: Delete post
      tags: [post]
      parameters:
        - in: path
          name: id
      responses:
        202:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/post'

  components:
    schemas:
  
      react:
        type: object
        properties:
      
          id:
            type: string
          type:
            type: string
          post:
            type: string
      post:
        type: object
        properties:
      
          id:
            type: string
          body:
            type: string
          title:
            type: string
          user:
            type: string
      user:
        type: object
        properties:
      
          id:
            type: number
          name:
            type: string
          email:
            type: string
          gender:
            type: string
          age:
            type: number
          password:
            type: string